name: Manual Build and Release Exo Packages

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Packages 📦
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone void-packages
        run: git clone --depth=1 https://github.com/void-linux/void-packages.git

      # This step caches the build environment to significantly speed up runs.
      - name: Cache hostdir
        id: cache-hostdir
        uses: actions/cache@v4
        with:
          path: void-packages/hostdir
          key: ${{ runner.os }}-xbps-hostdir-${{ hashFiles('void-packages/common/shlibs') }}

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar xz-utils ca-certificates

      - name: Download and install XBPS static binaries
        run: |
          wget https://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz
          tar xvf xbps-static-latest.x86_64-musl.tar.xz
          sudo install -Dm755 usr/bin/* /usr/local/bin/
      
      # This step creates the build environment only if it wasn't restored from cache.
      - name: Bootstrap XBPS-src
        if: steps.cache-hostdir.outputs.cache-hit != 'true'
        working-directory: void-packages
        run: |
          export XBPS_ARCH=x86_64
          ./xbps-src binary-bootstrap

      # This new step updates the build environment. It's the key fix for the 'build_style=none' error.
      - name: Update Bootstrap Environment
        working-directory: void-packages
        run: ./xbps-src bootstrap-update

      - name: Copy templates
        run: |
          mkdir -p void-packages/srcpkgs
          cp -r srcpkgs/* void-packages/srcpkgs/ 2>/dev/null || true

      - name: Allow restricted packages
        working-directory: void-packages
        run: echo XBPS_ALLOW_RESTRICTED=yes >> etc/conf

      # --- Build and Index Steps ---
      # The repository is now re-indexed after each package build.

      # - name: Build dart-sass
      #   working-directory: void-packages
      #   run: ./xbps-src pkg dart-sass

      # - name: Index local repository
      #   working-directory: void-packages
      #   run: xbps-rindex -a hostdir/binpkgs/*.xbps

      - name: Build ignis
        working-directory: void-packages
        run: ./xbps-src pkg ignis

      - name: Index local repository
        working-directory: void-packages
        run: xbps-rindex -a hostdir/binpkgs/*.xbps

      - name: Build ignis-gvc
        working-directory: void-packages
        run: ./xbps-src pkg ignis-gvc

      - name: Finalize repository index
        working-directory: void-packages
        run: xbps-rindex -a hostdir/binpkgs/*.xbps

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        with:
          name: exo-packages
          path: void-packages/hostdir/binpkgs/*.xbps
